default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: helpjuice_search_development
  username: postgres

test:
  <<: *default
  database: helpjuice_search_test
  username: postgres

production:
  <<: *default
  database: helpjuice-prod-db
  username: tgagudok
  url: postgres://tgagudok:7r2eqHO4qsvo2A_tRYuf0exbvmfa6Bqj@horton.db.elephantsql.com/tgagudok
  password: 7r2eqHO4qsvo2A_tRYuf0exbvmfa6Bqj
